sylius_grid:
    grids:
        setono_sylius_feed_admin_feed:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_feed.model.feed.class%"
            fields:
                name:
                    type: string
                    label: setono_sylius_feed.ui.name
                uuid:
                    type: string
                    label: setono_sylius_feed.ui.uuid
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    show:
                        type: show
                    delete:
                        type: delete
