setono_sylius_feed_admin_feed:
    resource: |
        alias: setono_sylius_feed.feed
        section: admin
        templates: "@SyliusAdmin/Crud"
        redirect: update
        grid: setono_sylius_feed_feed
        vars:
            all:
                subheader: setono_sylius_feed.ui.manage_feeds
                templates:
                    form: "@SetonoSyliusFeedPlugin/admin/feed/_form.html.twig"
            index:
                icon: rss
    type: sylius.resource

setono_sylius_feed_admin_feed_generate:
    path: /feeds/{id}/generate
    methods: [GET]
    defaults:
        _controller: 'Setono\SyliusFeedPlugin\Controller\Admin\GenerateFeedAction'

setono_sylius_feed_admin_feed_results:
    path: /feeds/{id}/results
    methods: [GET]
    defaults:
        _controller: 'Setono\SyliusFeedPlugin\Controller\Admin\FeedResultsAction'

setono_sylius_feed_admin_feed_preview:
    path: /feeds/{id}/preview
    methods: [GET]
    defaults:
        _controller: 'Setono\SyliusFeedPlugin\Controller\Admin\PreviewFeedAction'

setono_sylius_feed_admin_feed_publish_context:
    path: /feeds/{id}/publish/{contextKey}
    methods: [GET]
    defaults:
        _controller: 'Setono\SyliusFeedPlugin\Controller\Admin\PublishContextAnywayAction'
    requirements:
        contextKey: '[^/]+'

setono_sylius_feed_admin_lookup_table:
    resource: |
        alias: setono_sylius_feed.lookup_table
        section: admin
        templates: "@SyliusAdmin/Crud"
        redirect: update
        grid: setono_sylius_feed_lookup_table
        vars:
            all:
                subheader: setono_sylius_feed.ui.manage_lookup_tables
            index:
                icon: database
    type: sylius.resource

setono_sylius_feed_admin_lookup_table_refresh:
    path: /lookup-tables/{id}/refresh
    methods: [GET]
    defaults:
        _controller: 'Setono\SyliusFeedPlugin\Controller\Admin\RefreshLookupTableAction'
