setono_sylius_feed_admin_feed:
    resource: |
        alias: setono_sylius_feed.feed
        section: admin
        templates: '@SyliusAdmin\\Crud'
        redirect: show
        grid: setono_sylius_feed_admin_feed
        permission: true
        vars:
            all:
                subheader: setono_sylius_feed.ui.manage_feeds
            index:
                icon: 'file image outline'
    type: sylius.resource
