shop:
    resource: "routing/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

admin:
    resource: "routing/admin.yaml"
    prefix: /%sylius_admin.path_name%
