flysystem:
    storages:
        # Temporary storage where feeds are created
        # It is best that this storage is local (or some shared fast storage)
        # because we stream to this storage when creating feeds
        setono_sylius_feed.storage.local.feed_tmp:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/setono_sylius_feed/feed_tmp'
        setono_sylius_feed.storage.local.feed:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/setono_sylius_feed/feed'

framework:
    messenger:
        buses:
            setono_sylius_feed.command_bus: ~

sylius_grid:
    grids:
        setono_sylius_feed_feed:
            driver:
                name: doctrine/orm
                options:
                    class: '%setono_sylius_feed.model.feed.class%'
            fields:
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                format:
                    type: string
                    label: setono_sylius_feed.form.feed.format
                state:
                    type: string
                    label: setono_sylius_feed.ui.state
                lastGeneratedAt:
                    type: datetime
                    label: setono_sylius_feed.ui.last_generated_at
                    sortable: ~
                    options:
                        format: 'Y-m-d H:i'
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: '@SyliusUi/Grid/Field/enabled.html.twig'
            actions:
                main:
                    create:
                        type: create
                item:
                    generate:
                        type: default
                        label: setono_sylius_feed.ui.generate
                        icon: sync
                        options:
                            link:
                                route: setono_sylius_feed_admin_feed_generate
                                parameters:
                                    id: resource.id
                    results:
                        type: default
                        label: setono_sylius_feed.ui.results
                        icon: list
                        options:
                            link:
                                route: setono_sylius_feed_admin_feed_results
                                parameters:
                                    id: resource.id
                    update:
                        type: update
                    delete:
                        type: delete
